-- \i '/home/enrique/laravel/coope/aaa_baseDeDatos.sql'

--create database coope with owner coope;
--\c dgit_solicitudes;



INSERT INTO users
(id,  nombre,   ap_pat,    ap_mat,      usr,       activo, estatus,  priv,    tel,        mail,                 direccion,                 dateregistro,         membrefin,          password) VALUES
('2','Enrique','Scheinvar','Gottdiener','enrique', '1',    'act',    'root', '5512345678','admin@correo.prueba','Calle X no Y interior Z','2020-06-10 00:00:00','2024-07-25 00:00:00','$2y$10$vfx7l3Wtsv2S2ZsIVi4fNegvWfoF.Z7ftfLBniHHYRB/CGCq9gq/i'),
('3','Niza',   'Gámez',    'Tamariz',   'niza',    '1',    'act',    'teso', '5512345678','admin@correo.prueba','Calle X no Y interior Z','2020-06-10 00:00:00','2024-07-25 00:00:00','$2y$10$vfx7l3Wtsv2S2ZsIVi4fNegvWfoF.Z7ftfLBniHHYRB/CGCq9gq/i'),
('4','Camilo', 'Scheinvar','Gamez',     'camilo',  '1',    'act',    'admon','5512345678','admin@correo.prueba','Calle X no Y interior Z','2020-06-10 00:00:00','2024-07-25 00:00:00','$2y$10$vfx7l3Wtsv2S2ZsIVi4fNegvWfoF.Z7ftfLBniHHYRB/CGCq9gq/i'),
('5','Luciana','Scheinvar','Gamez',     'luciana', '1',    'reg',    'usr',  '5512345678','admin@correo.prueba','Calle X no Y interior Z','2020-06-10 00:00:00','2023-07-25 00:00:00','$2y$10$vfx7l3Wtsv2S2ZsIVi4fNegvWfoF.Z7ftfLBniHHYRB/CGCq9gq/i'),
('6','Chia',   'Scheinvar','Gottdiener','chia',    '1',    'pru',    'usr',  '5512345678','admin@correo.prueba','Calle X no Y interior Z','2020-06-10 00:00:00','2023-01-25 00:00:00','$2y$10$vfx7l3Wtsv2S2ZsIVi4fNegvWfoF.Z7ftfLBniHHYRB/CGCq9gq/i');


INSERT INTO productos
(id,activo,gpo,nombre,variantes,presentacion,entrega,venta,existencias,costo,precioact,precioreg,preciopub,proveedor,categoria,responsable,descripcion,img,orden,created_at,updated_at) VALUES
('2','0','Verduras','Limon persa',NULL,'1 kg','no','no','0','12.0','12.0','15.0','25.0','Agris','FrutasVerduras','Paola',NULL,NULL,'9999',NULL,NULL),
('3','1','Verduras','Aguacate',NULL,'1 kg','com1','si','0','35.0','35.0','40.0','40.0','BarzonAguacate','FrutasVerduras','Guadalupe','Aguacate criollo producido de manera agroecológico por familias de la organización El Barzón.','Aguacate_Barzon.jpeg','1',NULL,NULL),
('4','0','Alfajor','Alfajores',NULL,'8 pz','com1','no','0','95.0','95.0','110.0','115.0','Maria Chimal','CafeteriaAbarrotes','Maria',NULL,'Alfajor_Maria.jpeg','2',NULL,NULL),
('5','1','Amaranto','Barras Chocolate',NULL,'10 barras','com1','si','0','50.0','50.0','55.0','60.0','AmarantoHdz','GranoHarinaPan','Joel','Alegrías con chocolate elaborados con amaranto sembrado, procesado y comercializado por la cooperativa familiar Hernández de Xochimilco.','Am_ChocoBarras_AmarantoHdz.jpg','3',NULL,NULL),
('6','1','Amaranto','Churritos','Chipotle,Natural,Piquin','125 gr','com2','si','0','10.5','10.5','11.5','12.5','AmarantoHdz','GranoHarinaPan','Joel','Bolsitas de churritos elaborados a partir de harina de amaranto sembrado, cosechado, procesado y comercializado por la cooperativa familiar Hernández de Xochimilco.','Am_churrritos.jpeg','9999',NULL,NULL),
('7','1','Amaranto','Harina',NULL,'250 gr','com12','si','0','25.0','25.0','27.5','30.5','AmarantoHdz','GranoHarinaPan','Joel','Fresquísima harina de amaranto sembrado, tostado, molido y comercializado por la cooperativa familiar Amaranto Hernández','Am_harina.jpeg','9999',NULL,NULL),
('8','1','Amaranto','Mega Barra',NULL,'12 barras','comid','si','0','60.0','60.0','66.0','72.0','AmarantoHdz','GranoHarinaPan','Joel','Mega barra de alegría con piñón rosado, nuez, almendra, cacahuate y miel de abeja con piloncillo elaborado a partir de amaranto sembrado, procesado y comercializado por la cooperativa familiar Amaranto Hernández de Xochimilco.',NULL,'9999',NULL,NULL),
('9','1','Amaranto','Obleas','Coco,Choco','4 pz','com12','si','0','20.0','20.0','22.0','24.0','AmarantoHdz','GranoHarinaPan','Joel','Paquete con 4 frecas  obleas elaboradas con harina de amaranto de la cooperativa Hernández.','AmObleas.jpeg','9999',NULL,NULL),
('10','1','Amaranto','Tostado ',NULL,'250 gr','com12','si','0','12.0','12.0','13.0','14.5','AmarantoHdz','GranoHarinaPan','Joel','Paquetitos de fresquísimo amaranto tostado sembrado, procesado y comercializado por la cooperativa familiar Hernández.','Am_tostado.jpeg','9999',NULL,NULL),
('11','1','Belleza','Acondicionador',NULL,'500 ml','no','si','0','76.0','76.0','84.0','94.0','Incalli','Belleza','Niza',NULL,NULL,'9999',NULL,NULL),
('12','1','Belleza','Crema pro-jeunesse',NULL,'50ml','no','si','0','90.0','90.0','100.0','110.0','Incalli','Belleza','Niza',NULL,NULL,'9999',NULL,NULL),
('13','1','Belleza','Crema Corporal',NULL,'400 mL','no','si','0','130.0','130.0','150.0','160.0','Echerio','Belleza','Soledad','Crema de uso cotidiano, crada para mantener la humectación de la piel de todo el curpo, con una textura ligera que se absorbe fácilmente.<br>Contiene manteca de karité y aceite de prpita de uva, que otorgan luminosidad, mientras que el extracto botánico de Manzanilla, calma y suaviza la piel.',NULL,'9999',NULL,NULL),
('14','1','Belleza','Unguento Herbal vs dolor cabeza',NULL,'15 ml','no','si','0','52.0','52.0','57.0','67.0','Incalli','Belleza','Niza',NULL,NULL,'9999',NULL,NULL),
('15','1','Belleza','Unguento vs dolor muscular',NULL,'60 ml','no','si','0','71.0','71.0','78.0','88.0','Incalli','Belleza','Niza',NULL,NULL,'9999',NULL,NULL),
('16','1','Belleza','Pomada de eucalipto romero y tomillo',NULL,'60 ml','no','si','0','71.0','71.0','78.0','88.0','Incalli','Belleza','Niza',NULL,NULL,'9999',NULL,NULL),
('17','1','Belleza','Exfoliante Facial',NULL,'30 mL','no','si','0','80.0','80.0','95.0','105.0','Echerio','Belleza','Soledad','Indicado para todo tipo de piel, ayuda a eliminar de manera óptima las células muertas acumuladas en el rostro.<br>Su fórmula contiene polvo de cáscara de nuez, que por su naturaleza es 100% biodegradable, ayudando a disminuir el impacto al ambiente.<br>Además, contiene etracto botánico de manzaila que calma la piel. Dejando así una sensación de suavidad de luminosidad y suavidad en el cutis.',NULL,'9999',NULL,NULL),
('18','1','Belleza','Gel limpiador facial',NULL,'125 mL','no','si','0','100.0','100.0','120.0','125.0','Echerio','Belleza','Soledad','De uso diario, es ideal para cualquier tipo de piel. <br>Limpia a profundidad de forma suave, gracias a su fórmula libre de sulfatos, que permite remover las impurezas del cutis y cuello sin irritarlos.<br>Adicionado con extracto botánco dde manzanilla que calma y suaviza, dando como resultado una piel limpia y tersa.',NULL,'9999',NULL,NULL),
('19','0','Belleza','Gel refrescante para piernas 250',NULL,'250 ml','no','si','0','160.0','160.0','165.0','175.0','Echerio','Belleza','Soledad','Después de un largo día o de permanecer horas de pie, dale a tus pies y piernas un descaso con este gel que contiene exractor botánicos de Castaña de Indias, Centella Asiática y Caléndula. Estos activos fitocosméticos son conocidos por ayudar al aumento de la microcirculación y mejorar la uniformidad del tono de la  piel. <br>Además su formulación adicioada con mentol y el Alcanfor proporcionan un efecto calmente y de frescura. Contiene glicerina que suaviza la piel de las piernas.',NULL,'9999',NULL,NULL),
('20','1','Belleza','Gel refrescante para piernas 500',NULL,'500 ml','no','si','0','300.0','300.0','320.0','330.0','Echerio','Belleza','Soledad','Después de un largo día o de permanecer horas de pie, dale a tus pies y piernas un descaso con este gel que contiene exractor botánicos de Castaña de Indias, Centella Asiática y Caléndula. Estos activos fitocosméticos son conocidos por ayudar al aumento de la microcirculación y mejorar la uniformidad del tono de la  piel. <br>Además su formulación adicioada con mentol y el Alcanfor proporcionan un efecto calmente y de frescura. Contiene glicerina que suaviza la piel de las piernas.',NULL,'9999',NULL,NULL),
('21','1','Belleza','Bell-Leche de manos moka',NULL,'60 ml','no','si','0','45.0','45.0','51.0','61.0','Incalli','Belleza','Niza',NULL,NULL,'9999',NULL,NULL),
('22','1','Belleza','Bell- Oleo gel contorno de ojos',NULL,'5 g','no','si','0','80.0','80.0','95.0','105.0','Echerio','Belleza','Soledad','Diseñado para suavizar las líneas de expresión  y humectar el contorno de los hojos, gracias al aporte de la mentaca de karité y aceites vegetales de alta calidad. Enriqueceido con los extractos botánicos de Centella Asiática y Caléndula que ayudan a difuminar el aspecto de las ojeras. Contiene Glicerina, que propociona tersura a la delicada piel del contoro de los ojos. Es ideal para cualquier tipo de piel.',NULL,'9999',NULL,NULL),
('23','1','Belleza','Bell- Respirasol',NULL,'66 ml','no','si','0','108.0','108.0','120.0','130.0','Incalli','Belleza','Niza',NULL,NULL,'9999',NULL,NULL),
('24','0','Belleza','Bell- Sampoo 15 hierbas',NULL,'180 ml','no','si','0','95.0','95.0','105.0','120.0','Incalli','Belleza','Niza',NULL,NULL,'9999',NULL,NULL),
('25','0','Belleza','Bell- Shampoo Jardin citrico',NULL,'350 ml','no','si','0','108.0','108.0','120.0','130.0','Incalli','Belleza','Niza',NULL,NULL,'9999',NULL,NULL),
('26','1','Belleza','Bell- Shampoo de romero',NULL,'500 ml','no','si','0','80.0','80.0','90.0','100.0','Incalli','Belleza','Niza',NULL,NULL,'9999',NULL,NULL),
('27','0','Boing','Boing Botella',NULL,'1 botella','no','si','0','6.8','7.5','7.5','8.0','Pascual','CafeteriaAbarrotes','Guadalupe',NULL,NULL,'9999',NULL,NULL),
('28','0','Bolsas','Bolsa para Mandado','Rafia,Tela','1 pz','no','si','0','7.0','7.0','10.0','20.0','Enrique','Ocasion','Enrique',NULL,NULL,'9999',NULL,NULL),
('29','1','Café','Cafe en grano','Americano,Exprés,Grano','500 gr','com1','si','0','95.0','95.0','105.0','115.0','BarzonCafe','CafeteriaAbarrotes','Guadalupe','Medio kilo de café agroecológico, sembrado, cosechado, tostado, molido y producido en la comunidad de Pahuatlán en la Sierra Alta de Puebla. Comercializado directamente por su sembrador.',NULL,'9999',NULL,NULL),
('30','0','Cajeta','Cajeta de leche',NULL,'300 ml','com1','si','0','65.0','65.0','72.0','82.0','compañeras','CafeteriaAbarrotes','Maria',NULL,NULL,'9999',NULL,NULL),
('31','1','Canela','Canela en vara',NULL,'100 gr','no','si','0','40.0','40.0','45.0','55.0','Paola','CafeteriaAbarrotes','Paola',NULL,NULL,'9999',NULL,NULL);